### ISSUE TITLE
issue: auth-token is re-generated

### ISSUE THREAD

**Issue by NithishC** [Intech-mobile-app/flutter-mobile-app#30]

**Comment by Naveen-R-M** [comment]
Thats a serious problem dude..

**Comment by NithishC** [comment]
I think the mentor might be working on a test environment and so a new token is generated every time.

**Comment by NithishC** [comment]
Finally, auth token is required only for the user's existence and used as a header for all requests but the user data will not be affected due to the regeneration. 
Headers(must include):
#### ``` x-auth-token:<token>```
