### ISSUE TITLE
issue: workflow failed

### ISSUE THREAD

**Issue by NithishC** [Intech-mobile-app/flutter-mobile-app#49]
```flutter analyze``` returns an 1 issue 
```
info - Don't import implementation files from another package - lib\generated_plugin_registrant.dart:7:8 - implementation_imports
```

**Comment by Naveen-R-M** [comment]
Issue #49 is due to the generated_plugin_registrant.dart 

- Put that inside gitignore and see the problem resolves.

**Comment by NithishC** [comment]
The file already exists on ```.gitignore``` and I think that's isn't the problem

**Comment by NithishC** [comment]
just ignore this ```info``` error
