### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by bhaveshmangal** [Intech-mobile-app/flutter-mobile-app#51]
![Screenshot (66)_LI](https://user-images.githubusercontent.com/66433620/117458724-3aa0ac00-af68-11eb-95ef-9624786c5d93.jpg)

**Comment by AyuPatidar** [comment]
statusCode needs to be changed from int type to var type

**Comment by NithishC** [comment]
@AyuPatidar Request returns ``` Future<dynamic>```, so instead of ``` var``` try using ```dynamic``` and add await in front of the request.
```diff
+ dynamic statusCode =await UserRequest.createUser(user);
- var statusCode = UserRequest.createUser(user);
```

**Comment by Megatron1702** [comment]
@NithishC Adding await is throwing an error that the function should be async, but the function is already async.

**Comment by AyuPatidar** [comment]
Addressed the issue by changing the registerSociety.dart file
